name: "Checks and static analysis"

on:
  # Every day at 23:00.
  schedule:
    - cron: '* 23 * * *'
  # For every PR.
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run unit tests and code analyzers
      run: ./gradlew check
